/**
 * IPCA data loader — reads from the static JSON file exported by the Python pipeline.
 *
 * The file `public/dashboard/ipca.json` is generated by `data_fidc/scripts/refresh.py`
 * (production) or `export_plotly_sample_for_compass.py` (local dev) and served as a
 * static asset.  No direct calls to the IBGE API are made from the browser.
 */

const IPCA_URL = "/dashboard/ipca.json";

export type IpcaRow = {
  period: string;    // "202501"
  ano: number;
  mes: string;       // "JAN"
  numeroIndice: number | null;
  variacaoMes: number | null;
};

type IpcaPayload = {
  rows: IpcaRow[];
};

/** Load IPCA rows from the pre-baked static JSON. */
export async function loadIpca(): Promise<IpcaRow[]> {
  const res = await fetch(IPCA_URL);
  if (!res.ok) throw new Error(`Failed to load IPCA data: ${res.status} ${res.statusText}`);
  const payload: IpcaPayload = await res.json();
  return payload.rows ?? [];
}
